<!DOCTYPE HTML PUBLIC "html.dtd">
<html>
<HEAD>
<TITLE>
Link Grammar Miscellaneous Publications Mirror
</TITLE>
</HEAD>
<BODY BGCOLOR="ffffff">
<H1>Mirrors of Miscellaneous Publications</H1>


    <table class="sortable">
      <thead>
        <tr>
          <th>Filename</th>
          <th>Type</th>
          <th>Size <small>(bytes)</small></th>
        </tr>
      </thead>
      <tbody>

<!--
      <?
        $myDirectory=opendir(".");
        
        // Get each entry
        while($entryName=readdir($myDirectory)) {
          $dirArray[]=$entryName;
        }
        
        // Finds extensions of files
        function findexts ($filename) {
          $filename=strtolower($filename);
          $exts=split("[/\\.]", $filename);
          $n=count($exts)-1;
          $exts=$exts[$n];
          return $exts;
        }
        
        // Closes directory
        closedir($myDirectory);
        
        // Counts elements in array
        $indexCount=count($dirArray);

        // Loops through the array of files
        for($index=0; $index < $indexCount; $index++) {
        
          // Gets File Names
          $name=$dirArray[$index];
          $namehref=$dirArray[$index];
          
          // Gets Extensions 
          $extn=findexts($dirArray[$index]); 
          
          // Gets file size 
          $size=number_format(filesize($dirArray[$index]));
          
          // Cleans up . and .. directories 
          if($name=="."){$name=". (Current Directory)"; $extn="&lt;System Dir&gt;";}
          if($name==".."){$name=".. (Parent Directory)"; $extn="&lt;System Dir&gt;";}
          
          // Print 'em
          print("
          <tr>
            <td><a href='./$namehref'>$name</a></td>
            <td><a href='./$namehref'>$extn</a></td>
            <td><a href='./$namehref'>$size</a></td>
          </tr>");
          }
      ?>
-->
      </tbody>
    </table>
  
</body>
</html>
