/* 
 * Kernel Feature Integration Server Presentation File
 * Server presentation for kernel feature management interface
 * 
 * Copyright (C) 2024 Free Software Foundation, Inc.
 */

#define KERNEL_SERVER 1

#include <mach/kernel_feature.defs>