#define MACH_MSG_TYPE_UNSTRUCTURED 0
#define MACH_MSG_TYPE_BIT 0
#define MACH_MSG_TYPE_BOOLEAN 0
#define MACH_MSG_TYPE_INTEGER_16 1
#define MACH_MSG_TYPE_INTEGER_32 2
#define MACH_MSG_TYPE_CHAR 8
#define MACH_MSG_TYPE_BYTE 9
#define MACH_MSG_TYPE_INTEGER_8 9
#define MACH_MSG_TYPE_REAL 10
#define MACH_MSG_TYPE_INTEGER_64 11
#define MACH_MSG_TYPE_STRING 12
#define MACH_MSG_TYPE_STRING_C 12
#define MACH_MSG_TYPE_MOVE_RECEIVE 16
#define MACH_MSG_TYPE_MOVE_SEND 17
#define MACH_MSG_TYPE_MOVE_SEND_ONCE 18
#define MACH_MSG_TYPE_COPY_SEND 19
#define MACH_MSG_TYPE_MAKE_SEND 20
#define MACH_MSG_TYPE_MAKE_SEND_ONCE 21
#define MACH_MSG_TYPE_PORT_NAME 15
#define MACH_MSG_TYPE_PORT_RECEIVE 16
#define MACH_MSG_TYPE_PORT_SEND 17
#define MACH_MSG_TYPE_PORT_SEND_ONCE 18
#define MACH_MSG_TYPE_PROTECTED_PAYLOAD 23
#define MACH_MSG_TYPE_POLYMORPHIC -1
#define desired_complex_alignof 8
#define sizeof_pointer 8
#define sizeof_char 1
#define sizeof_short 2
#define sizeof_int 4
#define sizeof_long 8
#define sizeof_int64_t 8
#define sizeof_uint64_t 8
#define sizeof_float 4
#define sizeof_double 8
#define sizeof_uintptr_t 8
#define sizeof_intptr_t 8
#define sizeof_uintptr_t_in_bits 64
#define sizeof_mach_msg_header_t 32
#define sizeof_mach_msg_type_long_t 8
#define sizeof_mach_msg_type_t 8
#define vm_offset_size 8
#define vm_offset_size_in_bits 64
#define port_name_size 4
#define port_name_size_in_bits 32
